/**
 * Strict Zod contracts for `admin.system.*`.
 *
 * Implementation is split by subdomain under `./adminSystem/`; this file is the stable
 * public barrel so existing `.../contracts/adminSystem` import paths remain valid.
 */

export {
  adminSystemCancelDocumentRenderJobInputSchema,
  adminSystemCancelDocumentRenderJobOutputSchema,
  type AdminSystemDocumentRenderFeedStats,
  adminSystemDocumentRenderFeedStatsSchema,
  adminSystemDocumentRenderJobIdSchema,
  type AdminSystemDocumentRenderMaintenance,
  adminSystemDocumentRenderMaintenanceSchema,
  adminSystemDocumentRenderQueueRecentSchema,
  adminSystemDocumentRenderResolvedConfigSchema,
  type AdminSystemGetDocumentRenderSettings,
  type AdminSystemGetDocumentRenderSettingsOutput,
  adminSystemGetDocumentRenderSettingsOutputSchema,
  type AdminSystemGetDocumentRenderStatus,
  type AdminSystemGetDocumentRenderStatusOutput,
  adminSystemGetDocumentRenderStatusOutputSchema,
  adminSystemRetryDocumentRenderJobInputSchema,
  adminSystemRetryDocumentRenderJobOutputSchema,
  adminSystemRunDocumentRenderGcInputSchema,
  type AdminSystemRunDocumentRenderGcOutput,
  adminSystemRunDocumentRenderGcOutputSchema,
  type AdminSystemUpdateDocumentRenderSettingsInput,
  adminSystemUpdateDocumentRenderSettingsInputSchema,
  type AdminSystemUpdateDocumentRenderSettingsOutput,
  adminSystemUpdateDocumentRenderSettingsOutputSchema,
} from './adminSystem/documentRender';
export {
  type AdminSystemEnterpriseLookupConfig,
  adminSystemEnterpriseLookupConfigSchema,
  type AdminSystemGetEnterpriseLookupSettings,
  adminSystemGetEnterpriseLookupSettingsOutputSchema,
  type AdminSystemTestEnterpriseLookupProviderInput,
  adminSystemTestEnterpriseLookupProviderInputSchema,
  type AdminSystemTestEnterpriseLookupProviderOutput,
  adminSystemTestEnterpriseLookupProviderOutputSchema,
  type AdminSystemUpdateEnterpriseLookupSettingsInput,
  adminSystemUpdateEnterpriseLookupSettingsInputSchema,
  type AdminSystemUpdateEnterpriseLookupSettingsOutput,
  adminSystemUpdateEnterpriseLookupSettingsOutputSchema,
} from './adminSystem/enterpriseLookup';
export {
  type AdminSystemGetInfraSettings,
  type AdminSystemGetInfraSettingsOutput,
  adminSystemGetInfraSettingsOutputSchema,
  type AdminSystemInfraDependency,
  adminSystemInfraDependencySchema,
  type AdminSystemInfraSecretAction,
  type AdminSystemMailConfig,
  adminSystemMailConfigSchema,
  type AdminSystemObjectStorageConfig,
  adminSystemObjectStorageConfigSchema,
  type AdminSystemTestDependencyInput,
  adminSystemTestDependencyInputSchema,
  adminSystemTestDependencyOutputSchema,
  type AdminSystemTestDependencyReason,
  adminSystemTestDependencyReasonSchema,
  type AdminSystemUpdateInfraSettingsInput,
  adminSystemUpdateInfraSettingsInputSchema,
  type AdminSystemUpdateInfraSettingsOutput,
  adminSystemUpdateInfraSettingsOutputSchema,
} from './adminSystem/infra';
export {
  type AdminSystemGetInstanceRevisionsInput,
  adminSystemGetInstanceRevisionsInputSchema,
  adminSystemGetInstanceRevisionsOutputSchema,
  adminSystemInstanceRevisionSchema,
  type AdminSystemInstanceState,
  adminSystemInstanceStateSchema,
} from './adminSystem/instances';
export {
  type AdminSystemCancelJobInput,
  adminSystemCancelJobInputSchema,
  adminSystemCancelJobOutputSchema,
  type AdminSystemClearJobsInput,
  adminSystemClearJobsInputSchema,
  type AdminSystemClearJobsOutput,
  adminSystemClearJobsOutputSchema,
  type AdminSystemGetJobsInput,
  adminSystemGetJobsInputSchema,
  adminSystemGetJobsOutputSchema,
  type AdminSystemJob,
  adminSystemJobKindSchema,
  adminSystemJobSchema,
  type AdminSystemListJobsInput,
  adminSystemListJobsInputSchema,
  type AdminSystemListJobsOutput,
  adminSystemListJobsOutputSchema,
  type AdminSystemRetryJobInput,
  adminSystemRetryJobInputSchema,
  adminSystemRetryJobOutputSchema,
} from './adminSystem/jobs';
export {
  adminSystemAuthSnapshotStatusOutputSchema,
  type AdminSystemPrepareRestartInput,
  adminSystemPrepareRestartInputSchema,
  adminSystemPrepareRestartOutputSchema,
  type AdminSystemRequestRestartInput,
  adminSystemRequestRestartInputSchema,
  adminSystemRequestRestartOutputSchema,
} from './adminSystem/restart';
export {
  type AdminSystemGetSandboxPackageStatsInput,
  adminSystemGetSandboxPackageStatsInputSchema,
  type AdminSystemGetSandboxPackageStatsOutput,
  adminSystemGetSandboxPackageStatsOutputSchema,
  type AdminSystemGetSandboxSettings,
  type AdminSystemGetSandboxSettingsOutput,
  adminSystemGetSandboxSettingsOutputSchema,
  adminSystemSandboxNetworkSchema,
  type AdminSystemSandboxPackageStat,
  adminSystemSandboxPackageStatSchema,
  adminSystemSandboxProviderSchema,
  adminSystemSandboxPullPolicySchema,
  type AdminSystemSandboxSettingsConfig,
  adminSystemSandboxSettingsConfigSchema,
  type AdminSystemUpdateSandboxSettingsInput,
  adminSystemUpdateSandboxSettingsInputSchema,
  type AdminSystemUpdateSandboxSettingsOutput,
  adminSystemUpdateSandboxSettingsOutputSchema,
  SANDBOX_PACKAGE_MANAGERS,
  type SandboxPackageManager,
  sandboxPackageManagerSchema,
} from './adminSystem/sandbox';
export {
  type AdminSystemStatusApiRevokeInput,
  adminSystemStatusApiRevokeInputSchema,
  adminSystemStatusApiRevokeOutputSchema,
  type AdminSystemStatusApiRotateInput,
  adminSystemStatusApiRotateInputSchema,
  type AdminSystemStatusApiRotateOutput,
  adminSystemStatusApiRotateOutputSchema,
  type AdminSystemStatusApiView,
  adminSystemStatusApiViewSchema,
  STATUS_API_TOKEN_PATTERN,
} from './adminSystem/statusApi';
/**
 * Alert settings contracts. Owned by the alerts agent; re-exported here so
 * `admin.system` callers share one barrel.
 */
export * from './adminSystem/alerts';
export {
  type AdminSystemCapability,
  adminSystemCapabilityKeySchema,
  adminSystemCapabilitySchema,
  adminSystemDependencyErrorCategorySchema,
  adminSystemDependencyStatusSchema,
  type AdminSystemDocumentRenderHealth,
  adminSystemDocumentRenderHealthSchema,
  type AdminSystemGetStatusOutput,
  adminSystemGetStatusOutputSchema,
  type AdminSystemRecentEvent,
  adminSystemRecentEventSchema,
  type AdminSystemRuntimeError,
  adminSystemRuntimeErrorSchema,
  type AdminSystemSandboxHealth,
  adminSystemSandboxHealthSchema,
  type AdminSystemWorkerHealth,
  adminSystemWorkerHealthSchema,
  adminSystemWorkerStatusSchema,
} from './adminSystem/status';
