/**
 * Strict Zod contracts for platform agent catalog (admin + effective).
 *
 * Implementation is split by subdomain under `./platformAgents/`; this file is the stable
 * public barrel so existing `.../contracts/platformAgents` import paths remain valid.
 */

export {
  adminPlatformAgentArchiveInputSchema,
  adminPlatformAgentArchiveOutputSchema,
  adminPlatformAgentCreateInputSchema,
  adminPlatformAgentCreateOutputSchema,
  adminPlatformAgentDeleteInputSchema,
  adminPlatformAgentDeleteOutputSchema,
  adminPlatformAgentDependentSchema,
  adminPlatformAgentDependentsInputSchema,
  adminPlatformAgentDependentsOutputSchema,
  adminPlatformAgentDetailOutputSchema,
  adminPlatformAgentGetInputSchema,
  adminPlatformAgentGetOutputSchema,
  adminPlatformAgentListInputSchema,
  adminPlatformAgentListItemSchema,
  adminPlatformAgentListOutputSchema,
  adminPlatformAgentMutationOutputSchema,
  adminPlatformAgentProvisionDefaultInboxInputSchema,
  adminPlatformAgentProvisionDefaultInboxOutputSchema,
  adminPlatformAgentUploadAvatarInputSchema,
  adminPlatformAgentUploadAvatarOutputSchema,
  adminPlatformAgentRollbackInputSchema,
  adminPlatformAgentRollbackOutputSchema,
  adminPlatformAgentSaveInputSchema,
  adminPlatformAgentSaveOutputSchema,
  adminPlatformAgentSetDefaultInboxInputSchema,
  adminPlatformAgentSetDefaultInboxOutputSchema,
  adminPlatformAgentValidateDependenciesInputSchema,
  adminPlatformAgentValidateDependenciesOutputSchema,
  adminPlatformAgentVersionsListInputSchema,
  adminPlatformAgentVersionsListOutputSchema,
  platformAgentDependencyValidationOutputSchema,
  platformAgentPublicationOutputSchema,
} from './platformAgents/adminLifecycle';
export type { PlatformAgentAssignmentWarningCode } from './platformAgents/assignments';
export {
  adminPlatformAgentAssignmentListInputSchema,
  adminPlatformAgentAssignmentListOutputSchema,
  adminPlatformAgentAssignmentPreviewInputSchema,
  adminPlatformAgentAssignmentPreviewOutputSchema,
  adminPlatformAgentAssignmentRemoveInputSchema,
  adminPlatformAgentAssignmentRemoveOutputSchema,
  adminPlatformAgentAssignmentUpsertInputSchema,
  adminPlatformAgentAssignmentUpsertOutputSchema,
  PLATFORM_AGENT_ASSIGNMENT_WARNING_CODES,
  platformAgentAssignmentWarningCodeSchema,
} from './platformAgents/assignments';
export {
  platformAgentConnectorDependencyRefSchema,
  platformAgentDependencySnapshotSchema,
  platformAgentKeySchema,
  platformAgentModelDependencyRefSchema,
  platformAgentModelParametersSchema,
  platformAgentSkillDependencyRefSchema,
  platformAgentSystemKeySchema,
  platformAgentVersionConfigSchema,
  platformAgentVersionSchema,
} from './platformAgents/common';
export {
  platformAgentAssignmentSchema,
  platformAgentIdentityDraftSchema,
  platformAgentImmutableVersionSchema,
  platformAgentRolloutProjectionSchema,
  platformEffectiveAgentSchema,
} from './platformAgents/domain';
export {
  platformAgentEffectiveGetInputSchema,
  platformAgentEffectiveGetOutputSchema,
  platformAgentEffectiveListOutputSchema,
  platformAgentSetHiddenInputSchema,
  platformAgentSetHiddenOutputSchema,
} from './platformAgents/effective';
export {
  adminPlatformAgentDetailAggregateOutputSchema,
  adminPlatformAgentRolloutCancelInputSchema,
  adminPlatformAgentRolloutCancelOutputSchema,
  adminPlatformAgentRolloutGetInputSchema,
  adminPlatformAgentRolloutGetOutputSchema,
  adminPlatformAgentRolloutListInputSchema,
  adminPlatformAgentRolloutListOutputSchema,
  adminPlatformAgentRolloutOutputSchema,
  adminPlatformAgentRolloutRetryInputSchema,
  adminPlatformAgentRolloutRetryOutputSchema,
  adminPlatformAgentRolloutRollbackInputSchema,
  adminPlatformAgentRolloutRollbackOutputSchema,
  adminPlatformAgentRolloutStartInputSchema,
  adminPlatformAgentRolloutStartOutputSchema,
} from './platformAgents/rollout';
export type {
  AdminPlatformAgentArchiveInput,
  AdminPlatformAgentArchiveOutput,
  AdminPlatformAgentAssignmentListInput,
  AdminPlatformAgentAssignmentListOutput,
  AdminPlatformAgentAssignmentPreviewInput,
  AdminPlatformAgentAssignmentPreviewOutput,
  AdminPlatformAgentAssignmentRemoveInput,
  AdminPlatformAgentAssignmentRemoveOutput,
  AdminPlatformAgentAssignmentUpsertInput,
  AdminPlatformAgentAssignmentUpsertOutput,
  AdminPlatformAgentCreateInput,
  AdminPlatformAgentCreateOutput,
  AdminPlatformAgentDeleteInput,
  AdminPlatformAgentDeleteOutput,
  AdminPlatformAgentDependentsInput,
  AdminPlatformAgentDependentsOutput,
  AdminPlatformAgentDetailAggregateOutput,
  AdminPlatformAgentGetInput,
  AdminPlatformAgentGetOutput,
  AdminPlatformAgentListInput,
  AdminPlatformAgentListOutput,
  AdminPlatformAgentMutationOutput,
  AdminPlatformAgentProvisionDefaultInboxInput,
  AdminPlatformAgentProvisionDefaultInboxOutput,
  AdminPlatformAgentUploadAvatarInput,
  AdminPlatformAgentUploadAvatarOutput,
  AdminPlatformAgentRollbackInput,
  AdminPlatformAgentRollbackOutput,
  AdminPlatformAgentRolloutCancelInput,
  AdminPlatformAgentRolloutCancelOutput,
  AdminPlatformAgentRolloutGetInput,
  AdminPlatformAgentRolloutGetOutput,
  AdminPlatformAgentRolloutListInput,
  AdminPlatformAgentRolloutListOutput,
  AdminPlatformAgentRolloutRetryInput,
  AdminPlatformAgentRolloutRetryOutput,
  AdminPlatformAgentRolloutRollbackInput,
  AdminPlatformAgentRolloutRollbackOutput,
  AdminPlatformAgentRolloutStartInput,
  AdminPlatformAgentRolloutStartOutput,
  AdminPlatformAgentSaveInput,
  AdminPlatformAgentSaveOutput,
  AdminPlatformAgentSetDefaultInboxInput,
  AdminPlatformAgentSetDefaultInboxOutput,
  AdminPlatformAgentValidateDependenciesInput,
  AdminPlatformAgentValidateDependenciesOutput,
  AdminPlatformAgentVersionsListInput,
  AdminPlatformAgentVersionsListOutput,
  PlatformAgentEffectiveGetInput,
  PlatformAgentEffectiveGetOutput,
  PlatformAgentEffectiveListOutput,
} from './platformAgents/types';
