import { describe, expect, it } from 'vitest';

import {
  AITABLE_BASE_LIST_LIMIT,
  AITABLE_BASE_QUERY_MAX,
  AITABLE_BASE_QUERY_MIN,
  AITABLE_CELL_MAX,
  AITABLE_FIELDS_MAX,
  AITABLE_RECORD_QUERY_DEFAULT,
  AITABLE_RECORD_QUERY_MAX,
  AITABLE_RECORD_QUERY_TEXT_MAX,
  AITABLE_RECORDS_MAX,
  BROKER_TOKEN_MIN,
  CHILD_TIMEOUT_MS,
  DOC_MARKDOWN_MAX,
  DOC_QUERY_MAX,
  DOC_SEARCH_LIMIT_DEFAULT,
  DOC_SEARCH_LIMIT_MAX,
  DOC_TITLE_MAX,
  DOWNLOAD_TIMEOUT_MS,
  DRIVE_LIST_LIMIT,
  DRIVE_SEARCH_LIMIT_DEFAULT,
  DRIVE_SEARCH_LIMIT_MAX,
  GLOBAL_CONCURRENCY,
  LOGIN_CANCEL_LIST_MS,
  LOGIN_CANCEL_WAIT_MS,
  LOGIN_CHILD_MS,
  LOGIN_KEEP_MS,
  LOGIN_READY_MS,
  LOGIN_START_DEADLINE_MS,
  LOGOUT_CHILD_MS,
  LOGOUT_TOTAL_MS,
  MAX_BODY_BYTES,
  MAX_FILE_BYTES,
  MAX_PENDING_LOGINS,
  PROFILE_CACHE_MS,
  QUEUE_TIMEOUT_MS,
  RETENTION_INTERVAL_MS,
  RETENTION_MAX_AGE_MS,
  SHEET_APPEND_COLS_MAX,
  SHEET_APPEND_ROWS_MAX,
  SHEET_CELL_MAX,
  SHEET_READ_COLS_MAX,
  SHEET_READ_ROWS_MAX,
  STATUS_CHILD_MS,
  STATUS_QUEUE_MS,
  STDERR_CAP_BYTES,
  STDOUT_CAP_BYTES,
  VERSION_RETRY_MS,
  WIKI_NODE_LIMIT_DEFAULT,
  WIKI_NODE_LIMIT_MAX,
  WIKI_SPACE_LIMIT,
} from './constants.ts';

describe('contract limits', () => {
  it('matches the sidecar limits', () => {
    expect(BROKER_TOKEN_MIN).toBe(32);
    expect(MAX_BODY_BYTES).toBe(64 * 1024);
    expect(STDOUT_CAP_BYTES).toBe(1024 * 1024);
    expect(STDERR_CAP_BYTES).toBe(64 * 1024);
    expect(MAX_FILE_BYTES).toBe(20 * 1024 * 1024);
    expect(GLOBAL_CONCURRENCY).toBe(4);
    expect(QUEUE_TIMEOUT_MS).toBe(10_000);
    expect(CHILD_TIMEOUT_MS).toBe(50_000);
    expect(DOWNLOAD_TIMEOUT_MS).toBe(100_000);
    expect(STATUS_QUEUE_MS).toBe(5_000);
    expect(STATUS_CHILD_MS).toBe(15_000);
    expect(LOGOUT_CHILD_MS).toBe(10_000);
    expect(LOGOUT_TOTAL_MS).toBe(35_000);
    expect(PROFILE_CACHE_MS).toBe(10_000);
    expect(LOGIN_READY_MS).toBe(20_000);
    expect(LOGIN_START_DEADLINE_MS).toBe(25_000);
    expect(LOGIN_CANCEL_WAIT_MS).toBe(5_000);
    expect(LOGIN_CANCEL_LIST_MS).toBe(4_000);
    expect(VERSION_RETRY_MS).toBe(60_000);
    expect(LOGIN_CHILD_MS).toBe(16 * 60 * 1000);
    expect(LOGIN_KEEP_MS).toBe(30 * 60 * 1000);
    expect(MAX_PENDING_LOGINS).toBe(10);
    expect(RETENTION_INTERVAL_MS).toBe(6 * 60 * 60 * 1000);
    expect(RETENTION_MAX_AGE_MS).toBe(14 * 24 * 60 * 60 * 1000);
  });

  it('matches the docs and sheets ceilings', () => {
    expect(DOC_QUERY_MAX).toBe(200);
    expect(DOC_TITLE_MAX).toBe(100);
    expect(DOC_MARKDOWN_MAX).toBe(20_000);
    expect(DOC_SEARCH_LIMIT_MAX).toBe(10);
    expect(DOC_SEARCH_LIMIT_DEFAULT).toBe(5);
    expect(WIKI_SPACE_LIMIT).toBe(20);
    expect(WIKI_NODE_LIMIT_MAX).toBe(30);
    expect(WIKI_NODE_LIMIT_DEFAULT).toBe(20);
    expect(DRIVE_LIST_LIMIT).toBe(20);
    expect(DRIVE_SEARCH_LIMIT_MAX).toBe(10);
    expect(DRIVE_SEARCH_LIMIT_DEFAULT).toBe(5);
    expect(SHEET_APPEND_ROWS_MAX).toBe(50);
    expect(SHEET_APPEND_COLS_MAX).toBe(30);
    expect(SHEET_READ_ROWS_MAX).toBe(200);
    expect(SHEET_READ_COLS_MAX).toBe(30);
    expect(SHEET_CELL_MAX).toBe(500);
    expect(AITABLE_BASE_QUERY_MIN).toBe(2);
    expect(AITABLE_BASE_QUERY_MAX).toBe(100);
    expect(AITABLE_BASE_LIST_LIMIT).toBe(10);
    expect(AITABLE_RECORD_QUERY_MAX).toBe(50);
    expect(AITABLE_RECORD_QUERY_DEFAULT).toBe(20);
    expect(AITABLE_RECORDS_MAX).toBe(20);
    expect(AITABLE_FIELDS_MAX).toBe(50);
    expect(AITABLE_CELL_MAX).toBe(2000);
    expect(AITABLE_RECORD_QUERY_TEXT_MAX).toBe(200);
  });
});
