/**
 * Finite server-emitted platform audit `action` / `targetType` catalogs.
 *
 * Emitters (`PlatformAuditService.append`, reauth `denied.action`, direct
 * `platformAuditLogs` inserts) must use these tokens — never free-form strings.
 * Locale coverage tests assert en-US + zh-CN labels for every entry.
 */

export const AUDIT_ACTIONS = [
  'admin.agentTemplates.create',
  'admin.agentTemplates.delete',
  'admin.agentTemplates.importBuiltins',
  'admin.agentTemplates.reorder',
  'admin.agentTemplates.setEnabled',
  'admin.agentTemplates.update',
  'admin.agents.archive',
  'admin.agents.assignments.create',
  'admin.agents.assignments.remove',
  'admin.agents.assignments.update',
  'admin.agents.assignments.upsert',
  'admin.agents.create',
  'admin.agents.createVersion',
  'admin.agents.delete',
  'admin.agents.provisionDefaultInbox',
  'admin.agents.provisionTaskManager',
  'admin.agents.publish',
  'admin.agents.rollback',
  'admin.agents.rollouts.cancel',
  'admin.agents.rollouts.retry',
  'admin.agents.rollouts.rollback',
  'admin.agents.rollouts.start',
  // De-drafted agent write. `createVersion` / `publish` / `updateDraft` stay in the catalog
  // so historical log rows keep resolving to a label.
  'admin.agents.save',
  'admin.agents.setDefaultInbox',
  'admin.agents.updateDraft',
  'admin.agents.uploadAvatar',
  'admin.agents.validateDependencies',
  'admin.aiModels.applyImmediate',
  'admin.aiModels.batchToggle',
  'admin.aiModels.batchUpdate',
  'admin.aiModels.clear',
  'admin.aiModels.create',
  'admin.aiModels.deleteFromDraft',
  'admin.aiModels.reorder',
  'admin.aiModels.syncUpstream',
  'admin.aiModels.update',
  'admin.aiProviderOAuth.disconnect',
  'admin.aiProviderOAuth.initiateDeviceCode',
  'admin.aiProviderOAuth.pollAuthStatus',
  'admin.aiProviders.applyImmediate',
  'admin.aiProviders.archive',
  'admin.aiProviders.createDraft',
  'admin.aiProviders.delete',
  'admin.aiProviders.publish',
  'admin.aiProviders.rollback',
  'admin.aiProviders.test',
  'admin.aiProviders.updateDraft',
  'admin.branding.publish',
  'admin.branding.rollback',
  'admin.branding.save',
  'admin.branding.saveDraft',
  'admin.branding.uploadAsset',
  'admin.creds.createFile',
  'admin.creds.createKV',
  'admin.creds.createOAuth',
  'admin.creds.delete',
  'admin.creds.deleteByKey',
  'admin.creds.update',
  'admin.creds.uploadFile',
  'admin.audit.conversations.get',
  'admin.audit.conversations.list',
  'admin.audit.conversations.messages',
  'admin.audit.events.facets',
  'admin.audit.events.get',
  'admin.audit.events.list',
  'admin.audit.events.stats',
  'admin.audit.exports.cancel',
  'admin.audit.exports.create',
  'admin.audit.exports.download',
  'admin.audit.exports.get',
  'admin.audit.files.open',
  'admin.audit.exports.list',
  'admin.audit.exports.worker',
  'admin.audit.get',
  'admin.audit.legalHolds.create',
  'admin.audit.legalHolds.get',
  'admin.audit.legalHolds.list',
  'admin.audit.legalHolds.release',
  'admin.audit.list',
  'admin.audit.policy.get',
  'admin.audit.policy.update',
  'admin.audit.retention.cancel',
  'admin.audit.retention.dryRun',
  'admin.audit.retention.getRun',
  'admin.audit.retention.listRuns',
  'admin.audit.retention.run',
  'admin.audit.retention.status',
  'admin.audit.retention.worker',
  'admin.audit.users.search',
  'admin.audit.users.summary',
  'admin.audit.users.timeline',
  'admin.authSettings.update',
  'admin.connectors.applyImmediate',
  'admin.connectors.archive',
  'admin.connectors.createDraft',
  'admin.connectors.deleteDraft',
  'admin.connectors.discover',
  'admin.connectors.publish',
  'admin.connectors.publishNow',
  'admin.connectors.revokeAllBindings',
  'admin.connectors.rollback',
  'admin.connectors.setSharedAuthorization',
  'admin.connectors.test',
  'admin.connectors.updateBuiltinToolPolicy',
  'admin.connectors.updateDraft',
  'admin.identityProviders.create',
  'admin.identityProviders.delete',
  'admin.identityProviders.disable',
  'admin.identityProviders.disable.lkgAdvance',
  'admin.identityProviders.discover',
  'admin.identityProviders.publish',
  'admin.identityProviders.publish.requestLease',
  'admin.identityProviders.publish.requestReserved',
  'admin.identityProviders.rollback',
  'admin.identityProviders.rollback.requestLease',
  'admin.identityProviders.rollback.requestReserved',
  'admin.identityProviders.testStart',
  'admin.identityProviders.testTerminal',
  'admin.identityProviders.update',
  'admin.identityProviders.validateNetwork',
  // Retained for historical rows: the draft workflow was removed in favour of `.save`.
  'admin.managedResources.publish',
  'admin.managedResources.save',
  'admin.managedResources.saveDraft',
  'admin.modules.update',
  'admin.permission.denied',
  'admin.roles.replaceUserGlobalRoles',
  'admin.security.secretRotation.cancel',
  'admin.security.secretRotation.restart',
  'admin.security.secretRotation.retry',
  'admin.security.secretRotation.start',
  'admin.settings.applyImmediate',
  'admin.settings.getDraft',
  // publish/rollback/saveDraft/validateDraft retained for historical rows only.
  'admin.settings.publish',
  'admin.settings.rollback',
  'admin.settings.save',
  'admin.settings.saveDraft',
  'admin.settings.validateDraft',
  'admin.sidebarLayout.update',
  'admin.skills.applyImmediate',
  'admin.skills.archive',
  'admin.skills.create',
  'admin.skills.createBuiltinOverride',
  'admin.skills.createVersion',
  'admin.skills.publish',
  'admin.skills.publishNow',
  'admin.skills.rollback',
  'admin.skills.updateDraft',
  'admin.skills.validate',
  'admin.system.alerts.test',
  'admin.system.alerts.update',
  'admin.system.jobs.cancel',
  'admin.system.jobs.clear',
  'admin.system.jobs.retry',
  'admin.system.prepareRestart',
  'admin.system.requestRestart',
  'admin.system.statusApi.revoke',
  'admin.system.statusApi.rotate',
  'admin.taskTemplates.create',
  'admin.taskTemplates.delete',
  'admin.taskTemplates.importRecommendations',
  'admin.taskTemplates.reorder',
  'admin.taskTemplates.setEnabled',
  'admin.taskTemplates.update',
  'admin.users.ban',
  'admin.users.create',
  'admin.users.delete',
  'admin.users.disableTwoFactor',
  'admin.users.get',
  'admin.users.getAuditTrail',
  'admin.users.list',
  'admin.users.replaceGlobalRoles',
  'admin.users.revokeSessions',
  'admin.users.setPassword',
  'admin.users.unban',
  'connector.runtime.sharedCall',
  'content_moderation.cache.clear',
  'content_moderation.classifier.test',
  'content_moderation.record.reveal',
  'content_moderation.records.delete',
  'content_moderation.settings.update',
  'content_moderation.user.auto_ban',
  'dingtalk.approval.agree',
  'dingtalk.approval.append',
  'dingtalk.approval.comment',
  'dingtalk.approval.create',
  'dingtalk.approval.delete_template',
  'dingtalk.approval.redirect',
  'dingtalk.approval.refuse',
  'dingtalk.approval.revert',
  'dingtalk.approval.rule.create',
  'dingtalk.approval.rule.delete',
  'dingtalk.approval.rule.update',
  'dingtalk.approval.rule_executed',
  'dingtalk.approval.save_template',
  'dingtalk.approval.terminate',
  'dingtalk.calendar.create',
  'dingtalk.calendar.delete',
  'dingtalk.calendar.respond',
  'dingtalk.calendar.update',
  'dingtalk.personal.aitable.records.create',
  'dingtalk.personal.aitable.records.update',
  'dingtalk.personal.authorize',
  'dingtalk.personal.doc.append',
  'dingtalk.personal.doc.create',
  'dingtalk.personal.report.submit',
  'dingtalk.personal.revoke',
  'dingtalk.personal.sheet.append',
  'dingtalk.personal.todo.complete',
  'dingtalk.personal.todo.update',
  'dingtalk.todo.complete',
  'dingtalk.todo.create',
  'dingtalk.todo.delete',
  'dingtalk.todo.update',
  'enterprise_lookup.query',
  'network_proxy.engine.install',
  'network_proxy.engine.restart',
  'network_proxy.geodata.install',
  'network_proxy.outlet.select_node',
  'network_proxy.scopes.update',
  'network_proxy.settings.update',
  'network_proxy.subscription.create',
  'network_proxy.subscription.delete',
  'network_proxy.subscription.refresh',
  'network_proxy.subscription.update',
  'system.browser_profile.regenerate',
  'system.browser_profile.update',
  'system.dingtalk.approval_rule.disable',
  'system.email.send',
  'system.infra.document_render.update',
  'system.infra.enterprise_lookup.update',
  'system.infra.mail.update',
  'system.infra.object_storage.update',
  'system.infra.sandbox.update',
  'system.im_connector.update',
  'managedResource.legacyMutation',
  'platform.managed_policy.publish',
  'platform.provider.publish',
  'platform.roles.replace',
  'platform.settings.publish',
  'platform.skill.publish',
  'user.connectors.disconnect',
  'user.connectors.oauthCallback',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_SET: ReadonlySet<string> = new Set(AUDIT_ACTIONS);

/** Named handles for high-churn emitters (prefer over string literals). */
export const AUDIT_ACTION = {
  IDENTITY_PROVIDERS_PUBLISH: 'admin.identityProviders.publish',
  IDENTITY_PROVIDERS_ROLLBACK: 'admin.identityProviders.rollback',
  IDENTITY_PROVIDERS_DISABLE: 'admin.identityProviders.disable',
  IDENTITY_PROVIDERS_DISABLE_LKG_ADVANCE: 'admin.identityProviders.disable.lkgAdvance',
  IDENTITY_PROVIDERS_PUBLISH_REQUEST_RESERVED: 'admin.identityProviders.publish.requestReserved',
  IDENTITY_PROVIDERS_PUBLISH_REQUEST_LEASE: 'admin.identityProviders.publish.requestLease',
  IDENTITY_PROVIDERS_ROLLBACK_REQUEST_RESERVED: 'admin.identityProviders.rollback.requestReserved',
  IDENTITY_PROVIDERS_ROLLBACK_REQUEST_LEASE: 'admin.identityProviders.rollback.requestLease',
  SYSTEM_ALERTS_TEST: 'admin.system.alerts.test',
  SYSTEM_ALERTS_UPDATE: 'admin.system.alerts.update',
  SYSTEM_JOBS_CANCEL: 'admin.system.jobs.cancel',
  SYSTEM_JOBS_CLEAR: 'admin.system.jobs.clear',
  SYSTEM_JOBS_RETRY: 'admin.system.jobs.retry',
  SYSTEM_STATUS_API_REVOKE: 'admin.system.statusApi.revoke',
  SYSTEM_STATUS_API_ROTATE: 'admin.system.statusApi.rotate',
  SYSTEM_PREPARE_RESTART: 'admin.system.prepareRestart',
  SYSTEM_REQUEST_RESTART: 'admin.system.requestRestart',
  SYSTEM_BROWSER_PROFILE_REGENERATE: 'system.browser_profile.regenerate',
  SYSTEM_BROWSER_PROFILE_UPDATE: 'system.browser_profile.update',
  SYSTEM_DINGTALK_APPROVAL_RULE_DISABLE: 'system.dingtalk.approval_rule.disable',
  SYSTEM_INFRA_DOCUMENT_RENDER_UPDATE: 'system.infra.document_render.update',
  SYSTEM_INFRA_ENTERPRISE_LOOKUP_UPDATE: 'system.infra.enterprise_lookup.update',
  SYSTEM_INFRA_MAIL_UPDATE: 'system.infra.mail.update',
  SYSTEM_INFRA_OBJECT_STORAGE_UPDATE: 'system.infra.object_storage.update',
  SYSTEM_INFRA_SANDBOX_UPDATE: 'system.infra.sandbox.update',
  SYSTEM_IM_CONNECTOR_UPDATE: 'system.im_connector.update',
  DINGTALK_APPROVAL_AGREE: 'dingtalk.approval.agree',
  DINGTALK_APPROVAL_APPEND: 'dingtalk.approval.append',
  DINGTALK_APPROVAL_COMMENT: 'dingtalk.approval.comment',
  DINGTALK_APPROVAL_CREATE: 'dingtalk.approval.create',
  DINGTALK_APPROVAL_DELETE_TEMPLATE: 'dingtalk.approval.delete_template',
  DINGTALK_APPROVAL_REDIRECT: 'dingtalk.approval.redirect',
  DINGTALK_APPROVAL_REFUSE: 'dingtalk.approval.refuse',
  DINGTALK_APPROVAL_REVERT: 'dingtalk.approval.revert',
  DINGTALK_APPROVAL_RULE_CREATE: 'dingtalk.approval.rule.create',
  DINGTALK_APPROVAL_RULE_DELETE: 'dingtalk.approval.rule.delete',
  DINGTALK_APPROVAL_RULE_EXECUTED: 'dingtalk.approval.rule_executed',
  DINGTALK_APPROVAL_RULE_UPDATE: 'dingtalk.approval.rule.update',
  DINGTALK_APPROVAL_SAVE_TEMPLATE: 'dingtalk.approval.save_template',
  DINGTALK_APPROVAL_TERMINATE: 'dingtalk.approval.terminate',
  DINGTALK_CALENDAR_CREATE: 'dingtalk.calendar.create',
  DINGTALK_CALENDAR_DELETE: 'dingtalk.calendar.delete',
  DINGTALK_CALENDAR_RESPOND: 'dingtalk.calendar.respond',
  DINGTALK_CALENDAR_UPDATE: 'dingtalk.calendar.update',
  DINGTALK_PERSONAL_AITABLE_RECORDS_CREATE: 'dingtalk.personal.aitable.records.create',
  DINGTALK_PERSONAL_AITABLE_RECORDS_UPDATE: 'dingtalk.personal.aitable.records.update',
  DINGTALK_PERSONAL_AUTHORIZE: 'dingtalk.personal.authorize',
  DINGTALK_PERSONAL_DOC_APPEND: 'dingtalk.personal.doc.append',
  DINGTALK_PERSONAL_DOC_CREATE: 'dingtalk.personal.doc.create',
  DINGTALK_PERSONAL_REPORT_SUBMIT: 'dingtalk.personal.report.submit',
  DINGTALK_PERSONAL_REVOKE: 'dingtalk.personal.revoke',
  DINGTALK_PERSONAL_SHEET_APPEND: 'dingtalk.personal.sheet.append',
  DINGTALK_PERSONAL_TODO_COMPLETE: 'dingtalk.personal.todo.complete',
  DINGTALK_PERSONAL_TODO_UPDATE: 'dingtalk.personal.todo.update',
  DINGTALK_TODO_COMPLETE: 'dingtalk.todo.complete',
  DINGTALK_TODO_CREATE: 'dingtalk.todo.create',
  DINGTALK_TODO_DELETE: 'dingtalk.todo.delete',
  DINGTALK_TODO_UPDATE: 'dingtalk.todo.update',
  ENTERPRISE_LOOKUP_QUERY: 'enterprise_lookup.query',
  PERMISSION_DENIED: 'admin.permission.denied',
  MANAGED_RESOURCE_LEGACY_MUTATION: 'managedResource.legacyMutation',
} as const satisfies Record<string, AuditAction>;

export type AuditRequestBaseAction =
  typeof AUDIT_ACTION.IDENTITY_PROVIDERS_PUBLISH | typeof AUDIT_ACTION.IDENTITY_PROVIDERS_ROLLBACK;

export type AuditRequestKind = 'requestReserved' | 'requestLease';

/**
 * Derive idempotency reservation/lease audit actions from a base publish/rollback
 * action. Callers must not concatenate `.requestReserved` / `.requestLease` ad hoc.
 */
export const deriveAuditRequestAction = (
  base: AuditRequestBaseAction,
  kind: AuditRequestKind,
): AuditAction => {
  const action = `${base}.${kind}` as AuditAction;
  if (!AUDIT_ACTION_SET.has(action)) {
    throw new Error(`audit action not catalogued: ${action}`);
  }
  return action;
};

export const isAuditRequestBaseAction = (value: string): value is AuditRequestBaseAction =>
  value === AUDIT_ACTION.IDENTITY_PROVIDERS_PUBLISH ||
  value === AUDIT_ACTION.IDENTITY_PROVIDERS_ROLLBACK;

export const AUDIT_TARGET_TYPES = [
  'agent',
  'agent_dependency_validation',
  'agent_template',
  'audit_event',
  'audit_export',
  'audit_policy',
  'audit_retention_run',
  'authSettings',
  'branding',
  'connector',
  'connector_binding',
  'connector_governance',
  'content_moderation_record',
  'content_moderation_settings',
  'dingtalk_approval',
  'dingtalk_calendar',
  'dingtalk_personal',
  'dingtalk_todo',
  'email_delivery',
  'file',
  'identity_provider',
  'identity_provider_test',
  'identity_provider_validation',
  'im_connector',
  'infra_settings',
  'legal_hold',
  'managed_policy',
  'model',
  'network_proxy_engine',
  'network_proxy_settings',
  'network_proxy_subscription',
  'permission',
  'platform_global_credential',
  'platform_global_credential_upload',
  'platform_job',
  'provider',
  'secret_rotation',
  'settings',
  'settings_validation',
  'sidebarLayout',
  'skill',
  'system',
  'task_template',
  'topic',
  'user',
  'user_list',
] as const;

export type AuditTargetType = (typeof AUDIT_TARGET_TYPES)[number];

export const AUDIT_TARGET_TYPE_SET: ReadonlySet<string> = new Set(AUDIT_TARGET_TYPES);

export const AUDIT_TARGET_TYPE = {
  IDENTITY_PROVIDER: 'identity_provider',
  DINGTALK_CALENDAR: 'dingtalk_calendar',
  DINGTALK_PERSONAL: 'dingtalk_personal',
  DINGTALK_TODO: 'dingtalk_todo',
  PLATFORM_JOB: 'platform_job',
  SYSTEM: 'system',
  PERMISSION: 'permission',
  LEGAL_HOLD: 'legal_hold',
  USER: 'user',
  DINGTALK_APPROVAL: 'dingtalk_approval',
} as const satisfies Record<string, AuditTargetType>;
